version: '3'

services:
  im-master:
    image: im-master:0.0.1
    build: .
    container_name: im-master
    volumes:
      - /var/im2/backup:/app/public/backup
      - /var/im2/static:/app/public/static
      - /var/im2/db:/app/public/db
      - /var/im2/logs:/app/public/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 2m
    networks:
      mongonet:
      imnet:
      webnet:
    ports:
      - 2760:3000
    env_file:
      - .env.local

networks:
  mongonet:
    external: true
    name: mongonet
  imnet:
    external: true
    name: imnet
  webnet:
    external: true
    name: webnet
