version: '3'

services:
  im-master:
    image: idehweb/im-master:1.0.0
    volumes:
      - /var/im-master/backup:/app/public/backup
      - /var/im-master/static:/app/public/static
      - /var/im-master/db:/app/public/db
      - /var/im-master/logs:/app/public/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 15s
        window: 2m
    networks:
      mongonet:
      # imnet:
      webnet:
    env_file:
      - .env.local

networks:
  mongonet:
    external: true
    name: mongonet
  # imnet:
  #   external: true
  #   name: imnet
  webnet:
    external: true
    name: webnet
